<?php
/**
 * LRA Consulting - Subscription Handler
 * Handles newsletter and briefing signups
 */

header('Content-Type: application/json');

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $to = "info@lraconsulting.net";
    
    // Sanitize input
    $email = filter_var(trim($_POST["email"]), FILTER_SANITIZE_EMAIL);

    // Validate
    if (empty($email) || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
        http_response_code(400);
        echo json_encode(["status" => "error", "message" => "Please provide a valid work email."]);
        exit;
    }

    $subject = "New LRA Subscriber: $email";
    $email_content = "Subscription Request Details:\n\n";
    $email_content .= "Subscriber Email: $email\n";
    $email_content .= "Source: Website Newsletter/Briefing Portal\n\n";
    $email_content .= "---\nAutomatically generated by LRA Web Portal.";

    $headers = "From: LRA Web Portal <noreply@lraconsulting.net>\r\n";
    $headers .= "Reply-To: $email\r\n";
    $headers .= "X-Mailer: PHP/" . phpversion();

    if (mail($to, $subject, $email_content, $headers)) {
        http_response_code(200);
        echo json_encode(["status" => "success", "message" => "Successfully subscribed."]);
    } else {
        http_response_code(500);
        echo json_encode(["status" => "error", "message" => "System error. Please try again later."]);
    }

} else {
    http_response_code(403);
    echo json_encode(["status" => "error", "message" => "Invalid request method."]);
}
?>